version: '3.4'

services:
  # Customers Api & Sidecar
  microdelivery.customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=CustomersDb;User Id=sa;Password=admin12345!;TrustServerCertificate=true
    ports:
      - "8000:80"
  microdelivery.customers.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-customers-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Products Api & Sidecar
  microdelivery.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
    ports:
      - "8001:80"
  microdelivery.products.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-products-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Orders Api & Sidecar
  microdelivery.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
  microdelivery.orders.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-orders-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  # Shipping Api & Sidecar
  microdelivery.shipping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
  microdelivery.shipping.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-shipping-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Notifications Api & Sidecar
  microdelivery.notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"
  microdelivery.notifications.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-notifications-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

# Discount Api & Sidecar
  microdelivery.discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8005:80"
  microdelivery.discount.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-discount-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  
  # Other services
  redis:
    ports:
      - 6379:6379
  
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  sqlserver:
   environment:
        SA_PASSWORD: "admin12345!"
        ACCEPT_EULA: "Y"
   ports:
        - "1433:1433"
  
  rabbit:
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
        
  eventstore:
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
 
  smtp4dev:
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  mongo_data:
  eventstore-volume-data:
  eventstore-volume-logs:    