version: '3.4'

services:
  # Customers Api & Sidecar
  microdelivery.customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=CustomersDb;User Id=sa;Password=admin12345!;TrustServerCertificate=true
    ports:
      - "8000:80"
  microdelivery.customers.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-customers-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Products Api & Sidecar
  microdelivery.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
    ports:
      - "8001:80"
  microdelivery.products.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-products-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Orders Api & Sidecar
  microdelivery.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
  microdelivery.orders.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-orders-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  # Shipping Api & Sidecar
  microdelivery.shipping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
  microdelivery.shipping.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-shipping-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  # Notifications Api & Sidecar
  microdelivery.notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"
  microdelivery.notifications.api.dapr:
    command: ["./daprd",
      "-app-id", "microdelivery-notifications-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/configuration.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  
  # Other services
  redis:
    ports:
      - 6379:6379
  
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  sqlserver:
   environment:
        SA_PASSWORD: "admin12345!"
        ACCEPT_EULA: "Y"

volumes:
  mongo_data:

